-- Seed university data
INSERT INTO universities (slug, name, short_name, logo, exam_name, exam_fee, application_start, application_end, application_status, exam_dates, results_release, test_locations, requirements, admission_link)
VALUES
  (
    'up',
    'University of the Philippines',
    'UP',
    '/up-logo-maroon-university.jpg',
    'UPCAT',
    '₱500',
    'August 1, 2025',
    'September 15, 2025',
    'upcoming',
    '[{"date": "November 16, 2025", "note": "Main Exam Date"}]',
    'January 2026',
    ARRAY['UP Diliman, Quezon City', 'UP Los Baños, Laguna', 'UP Manila', 'UP Visayas, Iloilo', 'UP Mindanao, Davao', 'UP Baguio', 'UP Cebu'],
    ARRAY['Accomplished UPCAT Application Form', 'Recent 2x2 ID photo', 'Grade 10-11 Report Card (Form 138)', 'Certificate of Good Moral Character', 'Payment of application fee (₱500)'],
    'https://upcat.up.edu.ph'
  ),
  (
    'ateneo',
    'Ateneo de Manila University',
    'ADMU',
    '/ateneo-blue-eagle-logo.jpg',
    'ACET',
    '₱1,000',
    'July 1, 2025',
    'October 31, 2025',
    'upcoming',
    '[{"date": "September - November 2025", "note": "Multiple testing windows"}]',
    'December 2025 - January 2026',
    ARRAY['Ateneo de Manila University, Quezon City', 'Regional Testing Centers (Various locations)'],
    ARRAY['Online Application Form', 'Grade 9-11 Report Cards', '2x2 ID Photo (white background)', 'Valid email address', 'Payment of application fee (₱1,000)'],
    'https://ateneo.edu/admissions'
  ),
  (
    'dlsu',
    'De La Salle University',
    'DLSU',
    '/dlsu-green-archer-logo.jpg',
    'DCAT',
    '₱800',
    'August 1, 2025',
    'November 30, 2025',
    'upcoming',
    '[{"date": "October 2025 - January 2026", "note": "Rolling admissions"}]',
    '2-3 weeks after exam',
    ARRAY['DLSU Manila Campus', 'DLSU-D Dasmariñas', 'Regional Testing Centers'],
    ARRAY['Online Application via MyLaSalle', 'Grade 10-11 Report Cards', '2x2 ID Photo', 'Birth Certificate (PSA)', 'Application fee (₱800)'],
    'https://www.dlsu.edu.ph/admissions'
  ),
  (
    'ust',
    'University of Santo Tomas',
    'UST',
    '/ust-yellow-tiger-logo.jpg',
    'USTET',
    '₱1,500',
    'September 1, 2025',
    'December 15, 2025',
    'upcoming',
    '[{"date": "January 2026", "note": "Exact date TBA"}]',
    'February 2026',
    ARRAY['UST Main Campus, Manila', 'UST Legazpi, Albay', 'Regional Testing Centers'],
    ARRAY['Online Application Form', 'Grades 9-11 Report Cards', '2x2 ID Photo (white background)', 'Certificate of Good Moral Character', 'Application fee (₱1,500)'],
    'https://www.ust.edu.ph/admissions'
  ),
  (
    'mapua',
    'Mapúa University',
    'Mapúa',
    '/mapua-red-cardinal-logo.jpg',
    'MapúaAT',
    '₱700',
    'Year-round',
    'Rolling Admissions',
    'ongoing',
    '[{"date": "Year-round", "note": "Scheduled upon application"}]',
    'Within 1-2 weeks',
    ARRAY['Mapúa Intramuros, Manila', 'Mapúa Makati Campus'],
    ARRAY['Online Application Form', 'Grade 10-11 Report Cards', '2x2 ID Photo', 'Birth Certificate', 'Application fee (₱700)'],
    'https://www.mapua.edu.ph/admissions'
  ),
  (
    'feu',
    'Far Eastern University',
    'FEU',
    '/feu-green-and-gold-logo.jpg',
    'FEUCAT',
    '₱600',
    'August 2025',
    'January 2026',
    'upcoming',
    '[{"date": "Multiple dates", "note": "August 2025 - January 2026"}]',
    '2 weeks after exam',
    ARRAY['FEU Manila', 'FEU Diliman', 'FEU Alabang', 'FEU Cavite'],
    ARRAY['Online Application Form', 'Grade 9-11 Report Cards', '2x2 ID Photo', 'Application fee (₱600)'],
    'https://www.feu.edu.ph/admissions'
  ),
  (
    'pup',
    'Polytechnic University of the Philippines',
    'PUP',
    '/pup-maroon-logo-polytechnic.jpg',
    'PUPCET',
    '₱300',
    'October 2025',
    'December 2025',
    'upcoming',
    '[{"date": "January - February 2026", "note": "Regional dates vary"}]',
    'March 2026',
    ARRAY['PUP Sta. Mesa, Manila', 'PUP Branches Nationwide', 'Regional Campuses'],
    ARRAY['Online Application (iApply)', 'Grade 9-11 Report Cards', '2x2 ID Photo', 'Application fee (₱300)', 'Certificate of Residency (for regional)'],
    'https://www.pup.edu.ph/iapply'
  ),
  (
    'plm',
    'Pamantasan ng Lungsod ng Maynila',
    'PLM',
    '/plm-blue-manila-city-logo.jpg',
    'PLMAT',
    '₱300',
    'November 2025',
    'January 2026',
    'upcoming',
    '[{"date": "February 2026", "note": "Exact date TBA"}]',
    'March 2026',
    ARRAY['PLM Main Campus, Intramuros, Manila'],
    ARRAY['Online Application Form', 'Grade 9-11 Report Cards', '2x2 ID Photo', 'Proof of Manila Residency', 'Birth Certificate (PSA)', 'Application fee (₱300)'],
    'https://plm.edu.ph/admissions'
  ),
  (
    'adzu',
    'Ateneo de Zamboanga University',
    'ADZU',
    '/ateneo-zamboanga-blue-logo.jpg',
    'ADZUCAT',
    '₱500',
    'August 2025',
    'November 2025',
    'upcoming',
    '[{"date": "November - December 2025", "note": "Multiple schedules"}]',
    'January 2026',
    ARRAY['ADZU Main Campus, Zamboanga City', 'Select Regional Centers'],
    ARRAY['Online Application Form', 'Grade 9-11 Report Cards', '2x2 ID Photo', 'Good Moral Certificate', 'Application fee (₱500)'],
    'https://www.adzu.edu.ph/admissions'
  ),
  (
    'slu',
    'Saint Louis University',
    'SLU',
    '/slu-blue-baguio-logo.jpg',
    'SLUCAT',
    '₱800',
    'September 2025',
    'January 2026',
    'upcoming',
    '[{"date": "October 2025 - February 2026", "note": "Multiple testing dates"}]',
    '2-3 weeks after exam',
    ARRAY['SLU Main Campus, Baguio City', 'SLU Laboratory Elementary School'],
    ARRAY['Online Application Form', 'Grade 10-11 Report Cards', '2x2 ID Photo (white background)', 'Certificate of Good Moral Character', 'Application fee (₱800)'],
    'https://www.slu.edu.ph/admissions'
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  short_name = EXCLUDED.short_name,
  logo = EXCLUDED.logo,
  exam_name = EXCLUDED.exam_name,
  exam_fee = EXCLUDED.exam_fee,
  application_start = EXCLUDED.application_start,
  application_end = EXCLUDED.application_end,
  application_status = EXCLUDED.application_status,
  exam_dates = EXCLUDED.exam_dates,
  results_release = EXCLUDED.results_release,
  test_locations = EXCLUDED.test_locations,
  requirements = EXCLUDED.requirements,
  admission_link = EXCLUDED.admission_link,
  updated_at = NOW();
